// Chapter 2 — the dot-com bubble, 1999–2004. Real companies, approximate real
// (contemporary, split-adjusted) prices. The point of this era: it BREAKS what
// COVID taught. 2020 rewarded buying the crash; this crash fell for THREE YEARS
// and the index took fifteen to come back. Frameworks fail — that's the lesson.

export const DOTCOM_COLORS = { AMZN: '#f5b13c', CSCO: '#5b8cff', QCOM: '#b072ff', PETS: '#ff6fa5' };

export const ERA_DOTCOM = {
  id: 'dotcom',
  num: 2,
  requires: 'covid',
  title: 'The gold rush and the long winter',
  sub: '1999–2004 · the dot-com bubble',
  startLabel: 'January 1999',
  endLabel: 'December 2004',
  dates: ['Jan 1999', 'Mar 2000', 'Nov 2000', 'Sep 2001', 'Oct 2002', 'Dec 2004'],
  moods: ['boom', 'boom', 'tense', 'storm', 'storm', 'calm'],
  stormAt: [3, 4],
  alarmAt: 2,
  headlines: [
    'The internet gold rush. Anything with .com in its name is doubling — your barber has stock tips.',
    'Peak mania. The Nasdaq has quintupled in five years; new internet companies IPO and double by lunch.',
    'The air leaks out. The Fed has raised rates six times; the shakiest dot-coms are dying first.',
    'The long fall. Recession deepens after the September 11th attacks — two years in, still no floor.',
    'The bottom. The Nasdaq is down 78% from its peak. Nobody wants to hear the word "internet" again.',
    'The quiet rebuild. The survivors are growing again — the bottom passed and almost nobody noticed.',
  ],
  startWatch: ['MSFT', 'AAPL', 'CSCO'],
  salDarlings: ['PETS', 'QCOM'],
  darlingUntil: 3,
  companies: [
    { id: 'MSFT', name: 'Microsoft', biz: 'Windows and Office run nearly every computer on earth. The empire of the era.', prices: [35, 53, 34, 25, 22, 27] },
    { id: 'AAPL', name: 'Apple', biz: 'The beige-box computer maker. A faded icon trying to matter again under a returned founder.', prices: [10, 34, 10, 8, 7, 32] },
    { id: 'CSCO', name: 'Cisco', biz: 'Sells the routers and switches the internet runs on — the picks and shovels of the gold rush.', prices: [23, 77, 50, 12, 9, 19] },
    { id: 'AMZN', name: 'Amazon', biz: 'Sells books on the internet, and swears it will sell everything. Loses money on purpose to grow.', prices: [56, 67, 30, 6, 17, 40], cost: 150, xp: 4,
      teasers: [
        'A website that sells books is somehow worth billions. People say books are just the start.',
        'The book site now sells toys, tools, music. It also loses more money every quarter.',
        'The book site has crashed with everything else. The obituaries are being drafted.',
        'Down more than 90%. Still shipping more packages than ever, oddly.',
        'A magazine cover asks if it can survive. Its sales just hit a record.',
        'It just turned a real profit. Quietly. Almost nobody cared.',
      ] },
    { id: 'QCOM', name: 'Qualcomm', biz: 'Designs the chips inside wireless phones. Owns patents everyone else must pay for.', prices: [3, 70, 32, 24, 16, 42], cost: 250, xp: 6,
      teasers: [
        'Some phone-chip company is the best stock in America this year. Up more than 10x.',
        'The phone-chip company finished 1999 up 2,600%. Analysts say it doubles from here.',
        'The chip darling has been cut in half. Believers say the wireless future is intact.',
        'Half again. The patents still collect royalties on every phone sold.',
        'Down 80% from the top — while phones outsell PCs for the first time.',
        'The royalties compounded all along. It has tripled off the bottom.',
      ] },
    { id: 'PETS', name: 'Pets.com', biz: 'Sells dog food online, fronted by a famous sock-puppet mascot. Spends $4 shipping a $2 bag.', prices: [null, 6, 0.2, 0.1, 0.1, 0.1], cost: 200, xp: 5,
      teasers: [
        'A pet-supply website with a sock-puppet mascot is about to IPO. Sal already loves it.',
        'The sock puppet is on the Super Bowl. The stock is already below its IPO price.',
        'The sock-puppet company is liquidating — eleven months after going public.',
        'Gone. The domain redirects to a competitor.',
        'A business-school case study now. Not a stock.',
        'Trivia answer. Nothing more.',
      ] },
  ],
  info: {
    MSFT: [
      { m: 'Prints money; the most profitable software business ever built.', v: 'Expensive, like everything this year.', n: 'The government antitrust case is heating up.' },
      { m: 'Still hugely profitable.', v: 'Priced for an empire that never stumbles.', n: 'A judge just ruled it an illegal monopoly.' },
      { m: 'Profits fine; the stock is not.', v: 'Cheaper — the breakup threat hangs over it.', n: 'Talk of splitting the company in two.' },
      { m: 'Profits keep flowing through the recession.', v: 'Back to a normal price.', n: 'The breakup was overturned; a settlement nears.' },
      { m: 'Cash keeps piling up.', v: 'Cheap versus its own history.', n: 'The case settled. The drama is over; so is the growth story.' },
      { m: 'A money machine, growing slowly.', v: 'Reasonable, and it pays a dividend now.', n: 'The giant has gone quiet and steady.' },
    ],
    AAPL: [
      { m: 'Barely profitable; a niche player with loyal fans.', v: 'Cheap, because most people think it is finished.', n: 'The returned founder just launched a colorful all-in-one computer.' },
      { m: 'Small profits, improving.', v: 'Swept up in the mania like everything else.', n: 'The colorful computers are actually selling.' },
      { m: 'A shock profit warning; sales fell off a cliff.', v: 'Cut by more than half in one day.', n: 'The stock lost 52% in a single session in September.' },
      { m: 'Losing money again in the downturn.', v: 'Priced near its cash in the bank.', n: 'It just launched a little white music player. Reviewers shrug.' },
      { m: 'Small losses; the music player is a quiet hit.', v: 'Still priced as an afterthought.', n: 'An online music store just opened. Songs cost 99 cents.' },
      { m: 'Profitable again — the music business is exploding.', v: 'The comeback is getting priced in fast.', n: 'The white earbuds are suddenly everywhere.' },
    ],
    CSCO: [
      { m: 'Sales growing 50%+ a year; genuinely profitable.', v: 'Very expensive — priced as the backbone of the future.', n: 'Every company on earth is buying networking gear.' },
      { m: 'Still growing fast.', v: 'Briefly the most valuable company in the world.', n: 'Analysts say it could be the first trillion-dollar company.' },
      { m: 'Orders are suddenly being cancelled.', v: 'Down a third; still not cheap.', n: 'Customers overbought gear for years. The warehouses are full.' },
      { m: 'Sales collapsing; first layoffs ever.', v: 'Down 85% from the peak.', n: 'It wrote off billions in unsold inventory.' },
      { m: 'Stabilizing at a much smaller size.', v: 'Cheap-ish, if the internet keeps growing.', n: 'Still the backbone — just a fraction of the old price.' },
      { m: 'Growing modestly; very profitable again.', v: 'A normal price for a normal company now.', n: 'The gear still runs the internet. The magic is gone.' },
    ],
    AMZN: [
      { m: 'Sales doubling every year; loses money on every order.', v: 'Priced on a story, not on numbers.', n: 'The founder says profits are a choice it refuses to make yet.' },
      { m: 'Sales still exploding; losses too.', v: 'A famous analyst says the stock is worth double. Another says zero.', n: 'It is burning cash and selling bonds to keep going.' },
      { m: 'Growth slowing; the cash pile is shrinking.', v: 'Down 70% — and still arguably expensive.', n: 'A respected report questions whether it survives the year.' },
      { m: 'Still unprofitable, but gross sales keep climbing.', v: 'Priced for bankruptcy.', n: 'Down 90%+ from the peak. The obituaries are everywhere.' },
      { m: 'Its first small operating profit, ever.', v: 'Cheap if it lives; worthless if it does not.', n: 'The Christmas quarter might actually turn a real profit.' },
      { m: 'Profitable, growing 30%+ a year.', v: 'No longer cheap — the survivors got repriced.', n: 'It sells everything now, just like the founder said.' },
    ],
    QCOM: [
      { m: 'Royalties on every CDMA phone sold; very profitable.', v: 'Up 10x this year and climbing.', n: 'Its wireless standard is winning the phone wars.' },
      { m: 'Royalties compounding.', v: 'Finished 1999 up 2,600% — priced for the whole wireless future.', n: 'An analyst sets a price target double the current price.' },
      { m: 'Business fine; stock halved anyway.', v: 'Still expensive after the fall.', n: 'The mania is unwinding; even winners are being sold.' },
      { m: 'Royalties keep arriving through the recession.', v: 'Down 70% from the top.', n: 'Phones keep selling even in a downturn.' },
      { m: 'Solidly profitable; patents unchallenged.', v: 'A normal price for a real business.', n: 'Phones just outsold PCs for the first time.' },
      { m: 'Royalties on billions of phones a year now.', v: 'The recovery is well underway.', n: 'The wireless future arrived — later and quieter than promised.' },
    ],
    PETS: [
      { m: 'Not public yet.', v: 'Not public yet.', n: 'The IPO is being marketed everywhere.' },
      { m: 'Loses $4 shipping every $2 bag of dog food.', v: 'Below its IPO price within weeks.', n: 'The sock-puppet ad ran during the Super Bowl.' },
      { m: 'Out of cash; no one will lend more.', v: 'A penny stock.', n: 'Announced liquidation — eleven months after the IPO.' },
      { m: 'Liquidated.', v: 'Worthless.', n: 'The assets were sold off; the sock puppet was auctioned.' },
      { m: 'Gone.', v: 'Worthless.', n: 'A cautionary tale in every business textbook.' },
      { m: 'Gone.', v: 'Worthless.', n: 'Remembered fondly. The stock is not.' },
    ],
  },
  leads: [
    [{ id: 'QCOM', why: 'A phone-chip company is up 10x this year — mania, or the real future?' }],
    [{ id: 'PETS', why: 'The sock-puppet IPO. Sal is obsessed.' }, { id: 'AMZN', why: 'Books today, everything tomorrow — or so the founder says.' }],
    [{ id: 'CSCO', why: 'The bellwether of the boom is cracking for the first time.' }],
    [{ id: 'AMZN', why: 'Down 90%. Still shipping record packages. Bargain, or obituary?' }],
    [{ id: 'AAPL', why: 'A music player? From the beige-box company?' }],
    [],
  ],
  forces: [
    { id: 'NET', name: 'The internet gold rush', icon: '🌐', at: [0, 1], blurb: 'Everything with a website is being priced as the future.' },
    { id: 'RATES', name: 'Rate hikes', icon: '🏦', at: [1, 2], blurb: 'The Fed makes money expensive. Expensive dreams feel it first.' },
    { id: 'BUST', name: 'The long bust', icon: '🕳️', at: [2, 3, 4], blurb: 'The easy money is gone. Companies without profits are dying.' },
    { id: 'RECOV', name: 'The slow rebuild', icon: '🌱', at: [4, 5], blurb: 'Real businesses grind back while nobody is watching.' },
  ],
  truth: {
    NET: {
      CSCO: { dir: 'helps', note: 'The picks and shovels of the rush — briefly the most valuable company on earth.' },
      AMZN: { dir: 'helps', note: 'The mania funded its money-losing growth for years. The story was real; the price got silly.' },
      QCOM: { dir: 'helps', note: 'Up 2,600% in a single year. The gold rush made it a legend.' },
      MSFT: { dir: 'helps', note: 'The empire rode the boom too — right up until the judge spoke.' },
    },
    RATES: {
      CSCO: { dir: 'hurts', note: 'Expensive growth fell hardest when money got expensive — same lesson, different decade.' },
      QCOM: { dir: 'hurts', note: 'Even a real business halves when the multiple it borrowed deflates.' },
      AMZN: { dir: 'hurts', note: 'A cash-burning story stock is exactly what rate hikes kill first.' },
      AAPL: { dir: 'hurts', note: 'It fell with everything — though its own stumble did most of the damage.' },
      MSFT: { dir: 'hurts', note: 'Rates squeezed it too, with an antitrust judge pushing the same direction.' },
    },
    BUST: {
      PETS: { dir: 'hurts', note: 'It burned the cash and died — liquidated eleven months after its IPO. Zero is a real outcome.' },
      CSCO: { dir: 'hurts', note: 'Orders vanished; down 85% from the peak. Buying the dip lost money for two straight years.' },
      AMZN: { dir: 'hurts', note: 'From the peak to $6 — the story survived, the stock almost did not.' },
      QCOM: { dir: 'hurts', note: 'The bust dragged the winners down with the frauds.' },
      AAPL: { dir: 'hurts', note: 'A profit warning in the middle of it cut the stock in half in one day.' },
      MSFT: { dir: 'hurts', note: 'Even the giant drifted down for three straight years.' },
    },
    RECOV: {
      AMZN: { dir: 'helps', note: 'Profitable at last — the survivor tripled off the bottom while nobody watched.' },
      AAPL: { dir: 'helps', note: 'The iPod arrived. The comeback started before anyone called it one.' },
      QCOM: { dir: 'helps', note: 'The royalties compounded quietly the whole way back.' },
      CSCO: { dir: 'helps', note: 'It doubled off the bottom — to a fraction of the old dream.' },
    },
  },
  sal: {
    base: {
      0: { mood: 'hype', line: "Cuz!! Pets.com!! A SOCK PUPPET that sells dog food online! The second it IPOs, my whole bonus goes in!!", choices: [{ label: "That's… certainly a plan, Sal" }] },
      1: { mood: 'worried', line: "Mom's in the hospital again, cuz. I need $500 for the bills — everything I have is riding the market.", choices: [{ label: 'Give him $500', need: 500, help: true, eff: { cash: -500 }, note: 'Family. The rent still comes anyway.' }, { label: "I can't right now", refuse: true }] },
      2: { mood: 'worried', line: "My broker margin-called me, cuz. Float me $150 for groceries? The rebound is RIGHT there, I can feel it.", choices: [{ label: 'Lend him $150', need: 150, help: true, eff: { cash: -150 } }, { label: 'Not this time', refuse: true }] },
      3: { mood: 'greedy', line: "Guy in my chatroom swears Qualcomm and Amazon double from here. $200 for his newsletter. You in?", choices: [{ label: 'Buy the tip ($200)', need: 200, eff: { cash: -200, reveal: ['QCOM', 'AMZN'] }, note: 'You pay — then research them yourself.' }, { label: 'Pass' }] },
    },
    steal: { line: "Funny thing, cuz — you kept slamming the door on me. So I let myself in and 'borrowed' $700 from your drawer. Guess we're even now." },
    warn: { line: "You always show up for me, cuz, so here's your money back. And listen — get OUT. The internet thing is dead. It is NEVER coming back. Even I can see it now.", cash: 600, note: 'He pays you back — and begs you to quit at what history will call the bottom.' },
    plant: { mood: 'broke', line: "Everyone I know has left the market, cuz. Write it in that little bag of yours: the internet is DEAD — this recovery talk helps NOBODY.", plant: { force: 'RECOV', company: 'AMZN', dir: 'hurts' }, accept: "Write Sal's line in the pouch", decline: 'Sal… it might be the bottom', note: "His call, in your pouch. Free — but it's HIS." },
    final: { mood: 'manic', line: "AMAZON'S BACK, CUZ!! I KNEW IT ALL ALONG!! I'm taking a loan — ALL IN, it moons from here!!", allIn: 'AMZN',
      doLabel: 'Go all-in with Sal', doNote: "Every dollar of cash into Amazon, because Sal is sure.", wiseLabel: "No — I'll trust my own read", wiseNote: 'Size it yourself, like you learned.' },
    epi: {
      wise: "…You didn't chase it. All these years you just… looked for yourself, and sized it yourself. …Teach me that, cuz.",
      refused: "Round-tripped the whole thing to zero, cuz. Five years. Poof. …And yeah, the drawer thing — we're still not square.",
      helped: "I lost it all twice over — but you never let me sink all the way. That counted for more than the money, cuz.",
      neutral: "Five years, cuz. I rode it up 2,000% and back to zero. The sock puppet outlived my portfolio.",
    },
  },
  blurbs: {
    win: (net) => `You turned $4,000 into ${net} through the wildest bubble and the longest winter the market has ever had. That's escape velocity.`,
    winZh: (net) => `穿过市场史上最疯的泡沫和最长的寒冬，你把 $4,000 变成了 ${net}。这就是逃逸速度。`,
    survive: 'Five years, one bubble, one long winter — and you are still standing. Most people who started in 1999 cannot say that.',
    surviveZh: '五年，一场泡沫，一个漫长的寒冬——你还站着。1999 年入场的人，大多说不出这句话。',
  },
};
