// Night-school concept lessons: plain-language investing basics, each with one
// APPLICATION question (a tiny scenario, not recall) so the check means something.
// Reward is +1 insight — easier than reading a real case (+2), priced accordingly.

export const CONCEPTS = [
  {
    id: 'limit',
    term: 'Market order vs limit order',
    what: 'A market order buys right now, at whatever the price is this second. A limit order says "only buy if the price reaches MY number" — and waits.',
    example: 'A stock trades at $60. You would happily own it at $50. A limit order at $50 sits there and only fires if the price falls that far.',
    q: 'You think a stock is a great deal — but only if it drops from $80 to $65. What do you place?',
    opts: ['A market order right now', 'A limit order at $65', 'A limit order at $95'],
    answer: 1,
    why: 'A limit order at your price means you never overpay in the heat of the moment. The order does the discipline for you.',
  },
  {
    id: 'size',
    term: 'Position size — how big the bet is',
    what: 'WHAT you buy gets the attention; HOW MUCH decides your fate. The same right pick can make you rich at a bold size or barely matter at a tiny one — and the same wrong pick can sting or ruin you.',
    example: 'Two people bought the same stock that fell 60%. One had put in 5% of their money and shrugged. One had put in 80% and lost their apartment deposit.',
    q: 'You find a moonshot: it could triple, or it could go to zero. What is the sane size?',
    opts: ['All of it — conviction pays', 'Nothing — too risky to touch', 'A slice you could afford to lose entirely'],
    answer: 2,
    why: 'Moonshots are allowed — at a size where a total loss cannot break you. Size is how you survive being wrong.',
  },
  {
    id: 'diversify',
    term: 'Diversification — not one basket',
    what: 'Owning several different things means no single disaster can take you out. The pieces protect each other precisely because they do not move together.',
    example: 'In 2020, airlines collapsed while video-call stocks soared. Someone holding both barely wobbled. Someone holding only airlines lost half.',
    q: 'You own three delivery companies. Are you diversified?',
    opts: ['Yes — three is plenty', 'Not really — one story controls all three', 'Only if they are in different cities'],
    answer: 1,
    why: 'Diversification is about different STORIES, not different names. Three bets on the same story is one big bet.',
  },
  {
    id: 'avg',
    term: 'Averaging down — buying more as it falls',
    what: 'Buying more of something after it drops lowers your average cost. It is smart ONLY if the business is still fine and just cheaper — and a trap if the story itself broke.',
    example: 'Apple in the 2020 crash: same company, lower price — averaging down worked. Sears in 2014: the business was dying — every "cheap" buy just lost more.',
    q: 'Your stock fell 40%. When does buying more make sense?',
    opts: ['Always — it is 40% cheaper', 'Never — falling knives kill', 'Only if what you checked says the business itself is still sound'],
    answer: 2,
    why: 'The price falling is not information about whether to buy. The state of the business is. Check the story, not the chart.',
  },
  {
    id: 'pe',
    term: 'Price vs earnings — what you pay for what it earns',
    what: 'A stock is a claim on a company\'s profits. Compare the price to the yearly profit: paying 15x earnings is normal-ish; paying 100x means you are betting on a huge future that had better arrive.',
    example: 'Zoom in 2020 traded near 50x its SALES, never mind profits. The business kept growing — and the stock still fell 75%, because the price had assumed even more.',
    q: 'Two similar companies: one costs 12x its profit, the other 90x. What does the 90x price tell you?',
    opts: ['It is the better company', 'Huge growth is already priced in — it must over-deliver just to hold its price', 'It is about to crash'],
    answer: 1,
    why: 'A high multiple is not a verdict — it is a promise the company now has to keep. Expensive can keep winning, but the bar is brutal.',
  },
  {
    id: 'stop',
    term: 'Stop-loss — a pre-set exit',
    what: 'A stop-loss is an order that sells automatically if the price falls to your number. You decide the exit while calm, so panic never gets a vote.',
    example: 'You buy at $100 and set a stop at $85. A bad month takes it to $80 — you were out at $85 without having to watch, sweat, or "just wait a little longer."',
    q: 'What is the real point of a stop-loss?',
    opts: ['It guarantees you never lose money', 'It caps a loss at a size you chose in advance, with a calm head', 'It sells at the exact bottom'],
    answer: 1,
    why: 'Nothing prevents losses. A stop just makes sure the loss is the size you agreed to when you could still think straight.',
  },
  {
    id: 'index',
    term: 'Index fund — buying the whole market',
    what: 'Instead of picking winners, you can buy a tiny slice of EVERY big company at once. You give up the dream of the legendary pick and get the average — which quietly beats most professionals over time.',
    example: 'Through the 2020 crash and everything after, the whole-market fund holder never had to guess Zoom vs Delta. They owned both, and the average marched on.',
    q: 'Who is the index fund the right tool for?',
    opts: ['Only beginners', 'Anyone who wants the market\'s growth without betting on their own picks', 'People who cannot afford single stocks'],
    answer: 1,
    why: 'It is not a starter tool — it is the default that even great investors tell most people to use. Picking is optional; compounding is not.',
  },
  {
    id: 'short',
    term: 'Short selling — betting a price will fall',
    what: 'Shorting means selling borrowed shares now, hoping to buy them back cheaper later. If the price RISES instead, your loss has no ceiling — it can rise forever.',
    example: 'In 2021, funds shorting GameStop watched it jump 1,500% in weeks. A normal buyer can only lose what they put in; the shorts lost multiples of it.',
    q: 'What makes shorting more dangerous than buying?',
    opts: ['It is illegal in most places', 'A bought stock can only fall to zero; a shorted one can rise without limit', 'It costs more in fees'],
    answer: 1,
    why: 'Buying has a floor under the loss. Shorting does not — which is why being right eventually is not enough; you must also survive the meantime.',
  },
  {
    id: 'cash',
    term: 'Cash is a position too',
    what: 'Holding cash feels like doing nothing, but it is a choice: it loses a little to inflation each year — and it is the ONLY thing that lets you buy when everything goes on sale.',
    example: 'In March 2020 every stock was suddenly 30% off. Only the people holding cash could do anything about it. Everyone else could only watch.',
    q: 'The market just crashed and you are fully invested with no cash. What did you actually run out of?',
    opts: ['Luck', 'Options — you cannot buy the sale', 'Time'],
    answer: 1,
    why: 'Cash is stored choice. Its yield is invisible until the exact moment it is the most valuable thing you own.',
  },
];
